################################################################################
# Copyright (c) 2018 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential
################################################################################
[package]
name = "tb_tcon_start_done"

[dependencies.text_processing]
location = "ssh://git@bitbucket.metro.ad.selinc.com:7999/ccrtl/text_processing.git"
type = "git"
spec = {tagspec = '>=1.1.0,<2.0.0'}
