# Following rules apply in addition to toml standard content rules:
#   1) Main entity that is the top entity of this build is always referred to
#      by "top" toml record. See Record 1
#   2) The VHDL instance names (and not the entity name of the mapped
#      component) of internal components are names of asscociated toml records.
#      See Record 2-4
#   3) To explore generics of hierchical internal sub-components, provide
#      full hierarchical name of the instance name. See Record 5-6
#   4) A component's generic is a toml field in its toml record entry. See
#      Record 1-3
#   5) A toml field's value can be a string or a list. See Record 1-2
#   6) If a generic does not have a toml field entry, it will be unmodified.
#      See Record 3
#   7) If "OTHER_GENERICS" toml field is used, every generic that does not have
#      corresponding entry in its component map's toml record will be applied #        with the value of "OTHER_GENERICS". See Record 4-6
#   8) Three special values can be assigned to a toml field (generic):
#      1)  "__min__": The min value for the generic's ranges is used for
#                     exploration. This value only applies to generics which
#                     has a finite range. Thus string type, unconstrained
#                     integer/natural/positive type, and generics with fixed
#                     value generics are not affected not affected by it.
#                     A warning will be issued for each such instance
#      2)  "__max__": The max value for the generic's ranges is used for
#                     exploration. This value only applies to generics which
#                     has a finite range. Thus string type, unconstrained
#                     integer/natural/positive type, and generics with fixed
#                     value generics are not affected not affected by it.
#                     A warning will be issued for each such instance
#      3)  "__all__": All values from min to max in the generic's ranges will
#                     be used for exploration. This value only applies to
#                     generics which has a finite range. Thus string type,
#                     unconstrained integer/natural/positive type, and generics
#                     with fixed value generics are not affected not affected
#                     by it. A warning will be issued for each such instance

# Record 1
[top]
Generic_1 = "Generic_1 (string type) value(s)"
Generic_2 = "Generic_2 value(s)"

# Record 2
[inst1]
GENERIC_1 = [64, 128]
GENERIC_2 = "auto"

# Record 3
[inst2]
GENERIC_2 = "__all__"

# Record 4
[inst3]
GENERIC_1 = 0
OTHER_GENERICS = 16

# Record 5
[inst1.sub_inst1]
OTHER_GENERICS = "__max__"

# Record 6
[inst1.sub_inst1.sub_sub_inst1]
OTHER_GENERICS = "__min__"