################################################################################
# Copyright (c) 2019 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential
################################################################################
[package]
name = "tb_tcon_start_done_slave"
