################################################################################
# Copyright (c) 2018 Schweitzer Engineering Laboratories, Inc.
# SEL Confidential
################################################################################
[package]
name = "rtl_make"

[dependencies.build_rtl]
location = "ssh://git@bitbucket.metro.ad.selinc.com:7999/ccrtltools/build_rtl.git"
type = "git"
spec = {tagspec = '>=1.0.0,<2.0.0'}
